// Common-word lists for the non-English test languages (English uses the
// larger random-words list). About 200 of the most frequent words each, the
// same size as MonkeyType's base lists. Kept out of the package index so the
// client can load them only when someone picks a language.

import type { Language } from "./types.js";

const LISTS: Record<Exclude<Language, "english">, string> = {
  spanish: `de la que el en y a los se del las un por con no una su para es al lo como más o pero sus le ha me si sin sobre este ya entre cuando todo esta ser son dos también fue había era muy años hasta desde está mi porque qué sólo han yo hay vez puede todos así nos ni parte tiene él uno donde bien tiempo mismo ese ahora cada e vida otro después te otros aunque esa eso hace otra gobierno tan durante siempre día tanto ella tres sí dijo sido gran país según menos mundo año antes estado contra sino forma caso nada hacer general estaba poco estos presidente mayor ante unos les algo hacia casa ellos ayer hecho primera mucho mientras además quien momento millones esto españa hombre están pues hoy lugar madrid nacional trabajo otras mejor nuevo decir algunos entonces todas días debe política cómo casi toda tal luego pasado primer medio va estas sea tenía nunca poder aquí ver veces embargo partido personas grupo cuenta pueden tienen misma nueva cual fueron mujer frente josé tras cosas fin ciudad he social manera tener sistema será historia muchos juan tipo cuatro dentro nuestro punto dice ello cualquier noche aún agua parece haber situación fuera bajo grandes nuestra ejemplo acuerdo habían usted estados hizo nadie países horas posible tarde ley importante guerra desarrollo proceso realidad sentido lado mí tu cambio allí mano eran estar san número sociedad unas centro padre gente final relación cuerpo obra incluso través último madre mis modo problema cinco carlos hombres información ojos muerte nombre algunas público mujeres siglo todavía meses mañana esos nosotros hora muchas pueblo alguna dar problemas`,
  french: `le de un être et à il avoir ne je son que se qui ce dans en du elle au pour pas que vous par sur faire plus dire me on mon lui nous comme mais pouvoir avec tout y aller voir en bien où sans tu ou leur homme si deux mari moi vouloir te femme venir quand grand celui si notre devoir là jour prendre même votre tout rien petit encore aussi quelque dont tout mer trouver donner temps ça peu même falloir sous parler alors main chose toi mettre vie savoir yeux passer autre après regarder toujours puis jamais cela aimer non heure croire cent monde donc enfant fois seul autre entre vers chez demander jeune jusque très moment rester répondre tout tête père fille mille premier car entendre ni bon trois cœur ainsi an quatre un terre contre dieu monsieur voix penser quel arriver maison devant coup beau connaître devenir air mot nuit sentir vivre quelque pays dernier ciel frère porte grand vieux trop mort connaître reprendre femme sortir tenir partir fin nouveau lever ville pendant eau revenir nom parce toujours esprit rendre lieu rire tant rouge avoir long mourir sens gens bras corps cheval chambre table part moins loin blanc histoire milieu pied amour minute cause suivre ouvrir pouvoir figure mois idée fort seulement jour rue compter pas chemin point attendre route écrire mère guerre instant place visage matin question dormir soir ordre ami travail oublier monter pleurer jardin mémoire`,
  german: `der die und in den von zu das mit sich des auf für ist im dem nicht ein die eine als auch es an werden aus er hat dass sie nach wird bei einer um am sind noch wie einem über einen so zum war haben nur oder aber vor zur bis mehr durch man sein wurde sei in prozent hatte kann gegen vom können schon wenn habe seine mark ihre dann unter wir soll ich eines es jahr zwei jahren diese dieser wieder keine uhr seiner worden und will zwischen immer millionen was sagte gibt alle diesem seit muss wurden beim doch jetzt waren drei jahre mit neue neuen damit bereits da auch ihr seinen müssen ab ihrer nun wie ihren sagt sollen einmal kein viele weil lange schnell groß klein alt neu gut tag zeit hand haus welt leben kind frau mann land stadt arbeit geld wasser weg auge frage seite ende teil stunde nacht morgen abend woche monat freund mutter vater schule buch tisch tür fenster straße auto baum blume hund katze himmel sonne mond stern licht farbe rot blau grün weiß schwarz gehen kommen sehen machen sagen geben nehmen finden denken wissen stehen liegen sitzen laufen fahren spielen lernen lesen schreiben sprechen hören fragen antworten helfen kaufen essen trinken schlafen wohnen bleiben bringen halten zeigen fallen tragen ziehen öffnen schließen beginnen verstehen vergessen brauchen glauben lieben warten suchen`,
  portuguese: `de a o que e do da em um para é com não uma os no se na por mais as dos como mas foi ao ele das tem à seu sua ou ser quando muito há nos já está eu também só pelo pela até isso ela entre era depois sem mesmo aos ter seus quem nas me esse eles estão você tinha foram essa num nem suas meu às minha têm numa pelos elas havia seja qual será nós tenho lhe deles essas esses pelas este fosse dele tu te vocês vos lhes meus minhas teu tua teus tuas nosso nossa nossos nossas dela delas esta estes estas aquele aquela aqueles aquelas isto aquilo estou está estamos estão estive esteve estivemos estiveram estava estávamos estavam casa tempo vida dia ano homem mulher mundo país cidade coisa vez parte lugar trabalho família água amor noite tarde manhã semana mês hora nome caminho porta mão olho cabeça coração palavra livro escola amigo filho pai mãe irmão rua carro árvore sol lua céu mar terra fogo luz cor grande pequeno novo velho bom mau bonito feio alto baixo longo curto forte fraco rápido lento feliz triste fácil difícil primeiro último outro mesmo todo cada nenhum algum muito pouco ir vir ver fazer dizer dar ficar saber querer poder dever falar pensar olhar andar comer beber dormir viver morrer abrir fechar começar terminar ajudar precisar gostar achar deixar chegar sair entrar voltar levar trazer escrever ler ouvir sentir perder ganhar jogar cantar`,
  italian: `di e il la che a per un in è non una con del si da i le sono al della come ma ha lo più anche io se alla mi ci ho questo gli ne o suo nel tutto essere cosa molto sua solo mio bene dei loro fare mia quando lei due chi anni cui fatto così tempo ancora dove prima tra poi quello uno ora già dopo sempre questa nella stato può noi ogni perché lui sul casa vita giorno anno uomo donna mondo paese città parte volta lavoro famiglia acqua amore notte sera mattina settimana mese ora nome strada porta mano occhio testa cuore parola libro scuola amico figlio padre madre fratello sorella macchina albero sole luna cielo mare terra fuoco luce colore grande piccolo nuovo vecchio buono cattivo bello brutto alto basso lungo corto forte debole veloce lento felice triste facile difficile primo ultimo altro stesso tutti nessuno qualche molti pochi andare venire vedere dire dare stare sapere volere potere dovere parlare pensare guardare camminare mangiare bere dormire vivere morire aprire chiudere cominciare finire aiutare cercare trovare piacere lasciare arrivare uscire entrare tornare portare scrivere leggere sentire perdere vincere giocare cantare ballare comprare pagare aspettare chiamare capire credere conoscere prendere mettere tenere correre salire scendere passare restare rimanere cambiare lavorare studiare imparare insegnare ricordare dimenticare vivere sognare`,
  indonesian: `yang dan di itu dengan untuk tidak ini dari dalam akan pada juga saya ke karena tersebut bisa ada mereka lebih kami sudah atau hanya oleh sebagai banyak orang kita seperti setelah dia telah masih harus tahun saat bahwa belum tapi apa ia hari satu namun sangat dua baru lagi bagi kata agar semua jika maka anak rumah jalan kota negara dunia waktu kerja air api tanah langit laut gunung pohon bunga buah makan minum tidur bangun pergi datang pulang lihat dengar bicara tulis baca belajar ajar main kerja beli jual bayar tunggu cari temu tanya jawab buka tutup mulai selesai bantu pakai bawa ambil kasih terima pikir rasa ingat lupa suka cinta senang sedih marah takut berani besar kecil panjang pendek tinggi rendah baik buruk bagus jelek cepat lambat mudah sulit baru lama muda tua kaya miskin bersih kotor panas dingin terang gelap merah biru hijau kuning putih hitam pagi siang sore malam minggu bulan jam menit ibu ayah kakak adik teman guru murid dokter polisi mobil motor sepeda kereta pesawat kapal buku meja kursi pintu jendela kamar dapur sekolah kantor pasar toko uang harga nama kepala tangan kaki mata telinga mulut hati badan suara lagu cerita berita kabar soal jawaban pertanyaan masalah cara jalan hidup mati sehat sakit`,
  hinglish: `main tum aap hum woh yeh kya hai hain tha thi the nahi haan kaise kab kahan kyun kaun kitna kuch sab bahut thoda abhi phir aaj kal parso subah shaam raat din saal mahina hafta ghar kaam paani khana chai dost yaar bhai behen maa papa beta beti log aadmi aurat bachcha school kitaab gaana film raasta gaadi sheher gaon desh duniya waqt pyaar dil zindagi sapna baat kahani sawaal jawaab accha bura bada chhota naya purana lamba seedha asaan mushkil garam thanda khush udaas sundar tez dheere pehla aakhri dusra jana aana dekhna sunna bolna kehna karna dena lena khana peena sona uthna baithna chalna daudna padhna likhna sikhna sochna samajhna milna rehna rakhna lana le jana khelna gaana nachna hasna rona bhoolna yaad pata chahiye sakta sakti raha rahi rahe gaya gayi gaye kiya kiye diya liya mera meri mere tera teri tere uska uski unka hamara tumhara apna iska inka aur ya lekin par kyunki toh bhi hi na mat se ko ka ki ke mein pe tak liye saath bina upar neeche andar bahar aage peeche paas door yahan wahan jaldi zaroor shayad bilkul sirf pura aadha ek do teen char paanch das sau hazaar pehle baad mein`,
};

const cache = new Map<Language, string[]>();

// The words for a language (deduplicated, lower case where the language
// allows it). English returns an empty list: callers use random-words.
export function wordsFor(language: Language): string[] {
  if (language === "english") return [];
  let words = cache.get(language);
  if (!words) {
    words = [...new Set(LISTS[language].split(/\s+/).filter(Boolean))];
    cache.set(language, words);
  }
  return words;
}

// `count` random words from a language list, never the same word twice in a row.
export function randomWordsFor(language: Language, count: number, random: () => number = Math.random): string[] {
  const list = wordsFor(language);
  const out: string[] = [];
  while (out.length < count && list.length > 1) {
    const w = list[Math.floor(random() * list.length)];
    if (w !== out[out.length - 1]) out.push(w);
  }
  return out;
}
